# APIO project configuration file.
# For details see https://fpgawars.github.io/apio/docs/project-file

[env:default]
board = sipeed-tang-primer-20k
constraint-file = sipeed-tang-primer-20k.cst
top-module = top
